### ISSUE TITLE
Name of resource

### ISSUE THREAD

**Issue by alex070609** [Top-Serveurs/cfx-vote-plugin#2]
Hi,

Please be aware that the vote resource **NEEDS** to be name exactly _'vote'_ else the plugin will never be called and will never connect to the website.

### it has to do with line 3891 of the vote.js
`if (resourceName === 'vote') {`

### Maybe use this native

`GetCurrentResourceName();`

witch returns the name of the resource folder

**Comment by Metrakit** [comment]
fixed in the last PR. Thanks.
