### ISSUE TITLE
[Fivem] QBcore example

### ISSUE THREAD

**Issue by RaelesPLS** [Top-Serveurs/cfx-vote-plugin#4]
Hello ! Thanks for this script ! can you try do it for QBCore ?

**Comment by Matetv** [comment]
Ich glaube nicht, dass Sie es auf QBCore umschreiben! Ich schau es mir mal an und wenn es klappt werde ich es veröffentlichen!

**Comment by Metrakit** [comment]
Hello, we will take a look at implementing it in the following weeks. If someone does it before us, don't hesitate to open a PR; we would appreciate it.

**Comment by Matetv** [comment]
https://github.com/skypr0d/VoteTopServeur-QB/

**Comment by Davidoff333** [comment]
> https://github.com/skypr0d/VoteTopServeur-QB/

Oh was würde ich dich hochleben lassen wenn du es für VORP erstellst :-)

**Comment by Matetv** [comment]
> > https://github.com/skypr0d/VoteTopServeur-QB/
> 
> Oh was würde ich dich hochleben lassen wenn du es für VORP erstellst :-)

Vorp ist doch auf ESX Basis! Das sollte doch mit paar umstellungen auch so funktionieren!

**Comment by Metrakit** [comment]
We have just added a VORP example. For QBCore, yes you can use the example given by @Matetv

**Comment by MrburnsDV** [comment]
Yes pls i needed for QbCore
