### ISSUE TITLE
[Redm] Vorp example

### ISSUE THREAD

**Issue by bouyaka09** [Top-Serveurs/cfx-vote-plugin#6]
hello the team.  it would be possible to make it compatible with the vorp framework please.  THANKS

**Comment by Metrakit** [comment]
Hello, we will take a look at implementing it in the following weeks. If someone does it before us, don't hesitate to open a PR; we would appreciate it.

**Comment by Metrakit** [comment]
hello sorry for the late, we have just added a VORP example.
