### ISSUE TITLE
Untrusted IP

### ISSUE THREAD

**Issue by Maddnes95** [Top-Serveurs/cfx-vote-plugin#7]
Trusted IP list need to be updated.
If ever I reupload the trusted ip list to add new one I get token error.

**Comment by cmei94** [comment]
I have the same problem @Maddnes95  have you fixed it?

**Comment by Metrakit** [comment]
Have you contacted the support team? Normally the trusted IP list is up to date.

**Comment by Metrakit** [comment]
we have commited a fix about this issue
