### ISSUE TITLE
unable to connect 

### ISSUE THREAD

**Issue by Mistz-ik** [Top-Serveurs/cfx-vote-plugin#8]
I follow instruction, the console said "all is done" the port is good, the token is good too but when i try to test connectivity nothing append, and same for votes, idk why, no errors

**Comment by Metrakit** [comment]
Have you contacted the support team? Do you still have the issue?

**Comment by facoo34** [comment]
i have same problem, i contact support but they no contact me

**Comment by TekaAK** [comment]
same for me, I've contacted you and I still haven't had any answer

**Comment by Metrakit** [comment]
You can contact us by mail please.

**Comment by TekaAK** [comment]
Oui bonsoir, j'arrive pas a connecter mon serveur avec le plugin vote c
normal ?
